In [5]:
from numpy import random as rd

In [6]:
# Generate a random integer from 0 to 100:

#The randint() method takes a size parameter where you can specify the shape of an array.

x=rd.randint(100)
print(x)

35


In [7]:
# Generate a 2-D array with 3 rows, each row containing 5 random integers from 0 to 100:

x=rd.randint(100,size=(3,5))
print(x)

[[40 53  1 59  7]
 [97 31 30 74 25]
 [13  4  0 50 33]]


In [8]:
# The rand() method also allows you to specify the shape of the array

# Generate a 1-D array containing 5 random floats:

x=rd.rand(5) # floats only
print(x)

[0.2607321  0.31076943 0.19981029 0.51663457 0.09225804]


In [10]:
# Generate a 2-D array with 3 rows, each row containing 5 random numbers:

x=rd.rand(3,5)
print(x)

[[0.23632963 0.4710972  0.60656348 0.91737165 0.48045087]
 [0.97013786 0.42249968 0.07381641 0.89022977 0.73702148]
 [0.0847485  0.96351559 0.21099791 0.97636094 0.79988008]]


In [13]:
# The choice() method also allows you to return an array of values.

      #choice(<1 D array >,<size>)

array=rd.choice([2,3,4,5,6],size=(3,5))
print(array)



[[4 3 2 2 2]
 [6 5 6 6 6]
 [5 6 3 3 4]]
